FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache wget

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

RUN mkdir -p uploads data

EXPOSE 4000

CMD ["node", "--watch", "src/index.js"]
